Aleksandr sementsov
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #10
Opened 2021-02-09 08:29 UTC by shurasementsov

Всем здравствуйте!

Семенцов Александр 3540202/00201 уже выполнил 10 заданий. Запрашиваю проверку своих решений.
Выбираю: Эффективный индекс для анализа больших объемов данных уровней экспрессии генов.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam requested changes
У меня много как смысловых, так и стилистических замечаний. Я посмотрел еще не все, дальше буду смотреть после исправления уже найденного.

Также советую настроить `.gitignore` чтобы лишние файлы (.DS_Store) не оказывались в репозитории.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        int freq =0, freq2 = 0,freq3 = 0,freq4=0;
* Лучше настроить форматирование кода в IDE.
* В Java принято объявлять каждую переменную на отдельной строке, хотя можно делать и по другому

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +//Number of 't' are 211
Завершающая строка должна быть пустой

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +            if(c[i]=='A') {
Такое решение очень многословное. Попробуйте использовать массив с 4 элементами для нуклеотидов и делать внутренний цикл по нему.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +package com.company;
Ничего не означающие имена лучше избегать. Можно использовать default package.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        String s = "GACGTGGATTCACTGGCCTCCAAAGACAAAGACCAGGCGTTTGCTCGAGTTCACTCTCCTAGGAGCTCATCTACACCAGAAGGAGGAAAGGACACATGCTTTTACAGGGCACAGGGCCGCTAAATATATGCGTGTAATTCTATCAGGTGTTCATTATTAACGCGGGGGCATCAGCAGAA
В коде лучше не делать такие длинные строк. Можно прочитать из текстового файла.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-HAMM.java
> +        char[] c1 = s1.toCharArray();
Вызов [String.toCharArray()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#toCharArray()) создает новый массив и копирует содержимое строки в него. Это дополнительные расходы памяти - в этой задаче неважно, но лучше избегать.

Лучше использовать метод `String.charAt()`.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +        String pathCollection = "";
Я не очень понял что в этом методе происходит, но мне кажется что того же результата можно добиться гораздо короче, используя методы класса [java.nio.files.Path](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Path.html)

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +            return alphabet.toCharArray();
Почему бы здесь не возвращать `String`?

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +            while((c=reader.read()) != '\n'){
Для чтения строк можно использовать [java.util.Scanner](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Scanner.html)

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +    static int ParseWidth(FileReader reader) {
Названия методов в Java принято начинать с маленькой буквы

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +            return Integer.parseInt(width);
Здесь тоже можно использовать Scanner - метод `nextInt()`

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +    static char[] parsedAlphabet;
Есть какая-то необходимость использовать именно статические поля здесь? Может быть лучше сделать и поля и методы обычными?

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyPower.java
> +    public static int pow(int level, int number) {
А почему бы не использовать метод `Math.pow()`?

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyPower.java
> +    //builder pattern
Это не builder pattern

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/Main.java
> +        int[] indexes = new int[n];
Переменные `indexes` и `elements` нигде не используются. Может быть, их стоит удалить?

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +    //SubClasses
SubClass называют класс, наследующий от родительского.
ReWriter - это вложенный (nested) класс, а не подкласс.

Также непонятно вообще зачем он тут нужен.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +        static int[] buffer;
Здесь тоже непонятно зачем нужны статические поля.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +    int[][] minusMap;
Попробуйте дать этому полю, да и классу тоже, более понятное название.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +        public static int[] ReWrite(int[] sourceData) {
Здесь в названии стоило бы как-то отразить то, что массив записывается в обратном порядке.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +            catch (Exception e) { System.out.println("MinusMap is ready!"); }
Использовать исключения как часть control flow - довольно плохая практика, во всяком случае в Java так не принято. Тем более здесь непонятно откуда вообще это исключение, а также в этом месте ловятся вообще все исключения, а не только какое-то одно.

2021-02-09 15:59 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +    MinusMap(int n, int numeration) {
Этот конструктор выглядит очень похоже на `MinusMap(int n)`. Нельзя ли как-то вынести общий код чтобы избежать дублирования?

2021-02-10 07:36 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +    MinusMap(int n, int numeration) {
Я хотел использовать параметр по умолчанию. Но не нашёл этого в Java. Поэтому использовал перегрузку. Могу описать функцию, к которой будут обращаться все перегрузки этого конструктора.

2021-02-10 07:38 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +            catch (Exception e) { System.out.println("MinusMap is ready!"); }
Не знал, что обработчик исключений в Java является примером дурного тона. Я заменю на условие.

2021-02-10 07:41 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +        static int[] buffer;
Потому что для использования данного класса, нет необходимости создавать объект.

2021-02-10 07:42 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        String s = "GACGTGGATTCACTGGCCTCCAAAGACAAAGACCAGGCGTTTGCTCGAGTTCACTCTCCTAGGAGCTCATCTACACCAGAAGGAGGAAAGGACACATGCTTTTACAGGGCACAGGGCCGCTAAATATATGCGTGTAATTCTATCAGGTGTTCATTATTAACGCGGGGGCATCAGCAGAA
У меня в поздних работах реализован парсер. Могу и для этого решения внедрить его.

2021-02-10 12:55 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-HAMM.java
> +        char[] c1 = s1.toCharArray();
Понял. Спасибо, Дмитрий. Постараюсь учесть в оставшихся решениях.

2021-02-10 12:58 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +        String pathCollection = "";
Не спорю, это костыль. Мне просто очень нужна была пустышка, чтобы я мог обратиться к каталогу проекта, поэтому он на время инициализирует некий файл, который не имеет в названии слово "rosalind".

2021-02-10 13:00 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +            return alphabet.toCharArray();
До того, как я от Вас узнал про CharAt, видел это как вполне годный вариант реализации через массив символов. Планирую переписать этот и аналогичные участки кода.

2021-02-10 13:01 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +    static int ParseWidth(FileReader reader) {
Учту на будущее;)

2021-02-10 13:02 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/ExclusiveTxtPrsr.java
> +            return Integer.parseInt(width);
Да я видел. Но решил, чисто из спортивного интереса, этот вариант испробовать.

2021-02-10 13:03 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyPower.java
> +    public static int pow(int level, int number) {
Потому что данный метод выводит вещественное число, которое надо преобразовывать в целочисленное, а это, свою очередь лишние затраты.

2021-02-10 13:03 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyPower.java
> +    //builder pattern
Спасибо за замечание.

2021-02-10 13:04 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/Main.java
> +        int[] indexes = new int[n];
Они из моего предыдущего решения остались. Я их уберу.

2021-02-11 22:03 UTC, shurasementsov commented
Доброй ночи, Дмитрий! Я учёл все Ваши замечания. Жду отзыва.

2021-02-12 16:13 UTC, dmitrii-adamian-at-epam commented
Уберите, пожалуйста, .DS_Store из pull request.

2021-02-12 16:22 UTC, dmitrii-adamian-at-epam commented
Уберите, пожалуйста, файл на 530 тысяч строк - для git работа с такими файлами затруднительна.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam requested changes
Добавил еще порцию комментариев, но это далеко не все.
Еще работать и работать. Относитесь к коду аккуратнее, пожалуйста.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +            System.out.println(e.getMessage());
Это плохой способ обрабатывать исключения, лучше уж `e.printStackTrace()`. Большая часть информации об исключении теряется, `e.getMessage()` содержит мало информации.
Для таких задач проще всего просто добавить исключения в сигнатуру метода - они все равно будут выведены на печать.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +            scanner.close();
Используйте [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html)

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        char[] Nucleotids = {'A', 'C', 'G', 'T'};
* Переменные в Java принято называть с маленькой буквы
* `nucleotides`

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        for (int i = 0; i < 4; i++) {
`nucleotides.length` вместо 4

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +}
Последняя строка должна быть пустой

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-HAMM.java
> +        int freq =0;
Нет пробела после `=`

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-DNA.java
> +package com.company;
Уберите com.company - это бессмысленное название. Если хотите оставить пакет - сделайте `org.spbstu.practice` или что-нибудь в этом духе.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyPower.java
> +    public static int pow(int level, int number) {
Эти затраты совершенно незначительны, а Ваш метод просто некорректен (не поддерживает отрицательные степени). Не занимайтесь изобретением того что уже есть без необходимости.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyWriter.java
> +        {
В Java принят другой способ записи скобок, см. например [Google Code Style](https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style)

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/SaverOutput.java
> +        catch (Exception e) {}
Если исключение специально ловится и с ним ничего не делается - оно должно быть названо `ignored`. Желательно также указать почему это так делается.
Просто пропущенное исключения почти всегда ошибка.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/TranslationMap.java
> +public class TranslationMap {
У Вас 2 копии класса TranslationMap. Объедините в одну.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyWriter.java
> +public class MyWriter extends SaverOutput {
Класс `SaverOutput` не используется нигде кроме `MyWriter`. Причина существования `SaverOutput` неясна. Перенесите его методы в MyWriter и удалите его.

Также у Вас 3 копии `SaverOutput` - оставьте одну.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-PROT/Main.java
> +                        c[i+1] = 'Ъ';
Если Вы хотите использовать "магические" значения - сделайте для них именованные константы. Тот кто читает код должен понимать что происходит.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-PROT/Main.java
> +        char[] c1 = s1.toCharArray();
Измените название переменной на осмысленное, так чтобы читателю кода было понятно что эта переменная означает.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-PROT/Main.java
> +        for (int i = 0; i < c.length;) {
Индексы можно называть i, j только если их значение очевидно. Здесь не цикл по двумерной матрице, поэтому значение i, j не очевидно. Переименуйте так, чтобы значение переменных было понятно.

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-PRTM.java
> +        double[] z = {
Задавать эти значения двумя массивами - большой риск ошибиться.
Лучше создать Map при помощи [Map.ofEntries()](https://docs.oracle.com/javase/9/docs/api/java/util/Map.html#ofEntries-java.util.Map.Entry...-)

2021-02-12 16:45 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/BioinformStrong-REVC.java
> +//TCATATTCTCTTCTCGTTCAGGGGTCAGGCGCGTGCGCAGGACACGATAGGGCAGTGGCTGTATTGACACGCCGGAATTATCTCTCAGTCGCGCGAGTACATGTGAAGTTGAAAGAATACCGGACAGTATGGCCGTGGAAAGTTAATTTTGTTTAAGGCTTTACTGCCTGCAATGACCTCCACTCGCAGTCTGGGCC
Уберите, пожалуйста, настолько длинные строки из кода.

2021-02-12 17:01 UTC, shurasementsov commented
Я сейчас внёс изменения через терминал, но пока результаты нового коммита не видно.

2021-02-13 12:11 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/TranslationMap.java
> +public class TranslationMap {
Мне решения задач SIGN и PERM объединить в одну?

2021-02-13 15:39 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +        static int[] buffer;
> Потому что для использования данного класса, нет необходимости создавать объект.

В других языках аналогом статических полей является глобальные переменные. 

Общепринятый подход делать область видимости изменяемых объектов максимально маленькой. 

Если конкретно для этого задания одинаково подходит и локальная и глобальная переменная, то стоит выбрать общепринятый подход.

2021-02-13 15:44 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-LEXF/src/MinusMap.java
> +            catch (Exception e) { System.out.println("MinusMap is ready!"); }
> Не знал, что обработчик исключений в Java является примером дурного тона

В данном случае есть два момента:
- Сценарий когда `MinusMap is ready` работает через исключение. Именно об этом комментарий выше.
- Обработчик всех без разбора исключений который просто игнорирует ошибки является примером плохого тона.

2021-02-13 17:02 UTC, Cjkjvfnby requested changes
Я остановил ревью, подробности в комментариях. 

Эти моменты могут быть не очевидны, поэтому проговорю их явно.  Ревью - процесс затратный и  автор кода может сделать несколько шагов для упрощения этого процесса. 

1) Отформатировать код  (не руками! ИДЕ это умеет).  Это нужно делать перед каждым пушем, а лучше коммитом.
2) Запустить статический анализатор и обработать его комментарии (в рамках данной задачи ложных срабатываний скорее не будет совсем)
3) Сделать само ревью. То есть прочитать код как будто вы не автор.  Лучше подождать некоторое время после того как код написан.

Это сильно упрощает работу ревьювера и ускоряет весь процесс.

Работа с комментариями тоже имеет не очевидный момент:
Комментарий к строчке кода не всегда относится только к этому месту. Каждый раз нужно подумать, а есть ли еще в программе такие места, где это нужно исправить.  Такими например являются мои комментарии про короткое имя переменной, обработку исключения и комментарии в коде. 

То есть я ожидаю, что вы посмотрите на все комментарии в программе и поработаете с ними. Просмотрите все переменные и оцените насколько их имена соответствуют их содержимому, а также уберите обработку исключений, где это не нужно.

2021-02-13 17:02 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        return s;
Можно return s внести внутрь скобок.

А еще в разделе рефакторинга во многих IDE есть такая операция inline variable, я бы рекомендовал её здесь применить.

2021-02-13 17:02 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        catch (IOException e) {
Есть ли жизнь после исключения?  Есть ли смысл работать со значением по умолчанию?

Здесь можно не ловить исключение. Пусть лучше программа упадёт, чем посчитает результат от пустой строки.

2021-02-13 17:02 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        //To load a dataset
Такие комментарии не несут пользы.  От них можно избавится вынесением кода к которому они относятся в функцию с говорящем именем.  Именно это и сделано, значит комментарий можно удалить.  

`To load a dataset` и `getDataSet` звучат немного по разному, описывать одно и тоже явления разными словами считается дурным тоном, это добавляет сложности, но не приносит дополнительной пользы.

2021-02-13 17:02 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-DNA.java
> +            s = getDataSet("rosalind-DNA.txt");
Одно-буквенные имена можно использовать для переменных в счетчике.  Для остальных целей таких коротких имён стоит избегать.  Их очень любят в учебниках и задачниках, там они иногда уместны.

Именовать переменные в честь типа тоже плохо.  Это Джава, я и так знаю какого эта переменная типа, такой подход не даёт мне дополнительных знаний о том что происходит.  

Представьте себе читателя, который вообще не понимает какую задачу решает этот код.  Я как раз и есть пример такого читателя.  Я наверно могу применить дедукцию и по имени датасета найти что-же за задача решается, но мне хочется, чтобы это было очевидно из кода.  Именно именно переменных, классов и методов мне могут рассказать об этом.

2021-02-13 17:02 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        char[] nucleotids = {'A', 'C', 'G', 'T'};
Опечатка, правильно будет `nucleotides`.   Если используете IntelleJ Idea, то рекомендую плагин Grazi, он такие вещи помогает отлавливать.  

![image](https://user-images.githubusercontent.com/171597/107854885-11242880-6e30-11eb-8fa6-c846d81bc670.png)

2021-02-13 17:02 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-DNA.java
> +            for (int j = 0; j < s.length(); j++) {
Существует ли такая функция в Java которая может посчитать количество вхождения символа в строке?

2021-02-13 17:02 UTC, Cjkjvfnby commented on sementsov aleksandr/BioinformStrong-DNA.java
> +                if (s.charAt(j) == Nucleotids[i]) {
Здесь я заканчиваю ревью.  

Этот версия кода не работает и никогда не запускалась. Проверьте пожалуйста все свои задачи, что они работают и пере-запросите ревью.  Это нормально, такое случается, в жизни этот вопрос решается наличием тестов и автоматических сборок.  В рамках данной работы у нас к сожалению нет ни того ни другого и приходится делать всё руками. Для себя я бы сделал еще один файл запускатор всех задач, но его бы в репозиторий не добавлял.
 
Ревью кода который не работает может быть тратой времени ревьювера. У нас, к сожалению, ресурсы не бесконечны и мы не можем себе этого позволить.

2021-02-15 09:23 UTC, darina-ovis requested changes
много дубликатов кода. Если нравится работать с Java на уровне массивов, то следует вынести это в отдельные классы, чтобы избавиться от дубликатов. Хорошо уметь написать базовые функции с нуля для учебных целей, но в реальной жизни гораздо полезнее знать и уметь пользоваться тем, что уже написано.

2021-02-15 09:23 UTC, darina-ovis commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyWriter.java
> +
code duplicate.  Как вариант,
    static void goSave() {
         goSave("output.txt")
    }

2021-02-15 09:23 UTC, darina-ovis commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyWriter.java
> +            writer = new FileWriter("output.txt", StandardCharsets.UTF_8);
"output.txt" - рекомендуется выносить константы

2021-02-15 09:23 UTC, darina-ovis commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyWriter.java
> +    static void goSave() {
Не очень понимаю, зачем слово go в назнании метода. Мне кажется, оно смысла не добавляет

2021-02-15 09:23 UTC, darina-ovis commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyWriter.java
> +        catch (Exception e) {
перехват ошибок в этом духе называется pokemon exception handling, обычно его стараются избегать. Ловят те ошибки, которые ожидают получить и соответственно правильно их обработать.

2021-02-15 09:23 UTC, darina-ovis commented on sementsov aleksandr/BioinformStrong-LEXF/src/TranslationMap.java
> +    public int getMap(int[] numberArray, int counter) {
этот метод нарушает принцип single responsibility. Он печатает матрицу и возвращает counter. 
также название метода getMap предполагает, что возращать он будет Map, но возвращает int.

2021-02-15 09:23 UTC, darina-ovis commented on sementsov aleksandr/BioinformStrong-PROT/Main.java
> +                    if (proteinTable.charAt(tableIndex+4) != 'Ы') {
Что это 'Ы'?

2021-02-16 08:54 UTC, Kirvolque commented on sementsov aleksandr/BioinformStrong-PROT/Main.java
> +                "UGG W CGG R AGG R GGG G ";
Может лучше хранить эту табличку в виде `Map` ?
Или хранить её в таком виде в файле, но читать в мапу.

2021-02-19 17:26 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-PROT/Main.java
> +                    if (proteinTable.charAt(tableIndex+4) != 'Ы') {
Это у меня так обозначается "Stop"-символ таблице протеинов. Заменю на константу, чтобы было понятнее к прочтению кода.

2021-02-19 18:24 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-LEXF/src/MyWriter.java
> +
Понял. Спасибо огромное за совет! Это, если я правильно понял, решение устранения дублирования в перегрузках.

2021-02-19 18:59 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-DNA.java
> +            for (int j = 0; j < s.length(); j++) {
Спасибо за замечание. Порывшись нашёл счётчик вхождений, только моя IDE не может найти библиотеку common в apache. Поэтому я в будущем решении воспользовался методами filter. count.

2021-02-19 19:00 UTC, shurasementsov commented on sementsov aleksandr/BioinformStrong-DNA.java
> +        char[] nucleotids = {'A', 'C', 'G', 'T'};
В будущих решениях, где только можно, уже исправил орфографические ошибки с помощью анализатора.

2021-04-01 17:26 UTC, shurasementsov commented
Hello, everyone!

I have pushed the last rosalind's solutions, maybe. In this push:
all your comments are listened;
code is analyzed;
rosalind's tasks are repeated (everywhere are good score).

2021-04-02 13:25 UTC, dmitrii-adamian-at-epam approved these changes
Уберите, пожалуйста, всё, не относящееся к задачам - части кода по проекту, CSV файлы, конфигурацию IDEA. А также почините конфликт.

Код, мягко говоря, все ещё далёк от приемлемого качества, но смысла тратить своё время на его разбор я больше не вижу. Поэтому одобряю pull request.

2021-04-02 13:25 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/bioionformatika/notbig.csv
> +#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00096	HG00101	HG00103	HG00105	HG00107	HG00108	HG00109	HG00112	HG00113	HG00114	HG00115	HG00116	HG00117	HG00119	HG00126	HG00129	HG00131	HG00136	HG00138
А это точно относится к задачам Rosalind?

2021-04-02 13:25 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/bioionformatika/out/production/bioionformatika/GenotypeSearch/MinimalSearch/notbig.csv
> +#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00096	HG00101	HG00103	HG00105	HG00107	HG00108	HG00109	HG00112	HG00113	HG00114	HG00115	HG00116	HG00117	HG00119	HG00126	HG00129	HG00131	HG00136	HG00138
Это тоже кажется не из того репозитория.

2021-04-02 13:25 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/bioionformatika/src/com/company/Mainn.java
> +	// write your code here
Этот файл не содержит никакого осмысленного кода.

2021-04-02 13:25 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/bioionformatika/src/GenotypeSearch/MinimalSearch/notbig.csv
> +#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00096	HG00101	HG00103	HG00105	HG00107	HG00108	HG00109	HG00112	HG00113	HG00114	HG00115	HG00116	HG00117	HG00119	HG00126	HG00129	HG00131	HG00136	HG00138
Это тоже не из этого pull request.

2021-04-02 13:25 UTC, dmitrii-adamian-at-epam commented on sementsov aleksandr/bioionformatika/src/GenotypeSearch/MinimalSearch/Main.java
> +package GenotypeSearch.MinimalSearch;
Это не относится к задачам Rosalind.

2021-04-03 10:44 UTC, merged