Resolve 10 tasks from Rosalind
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #11
Opened 2021-02-12 20:43 UTC by marsofandrew

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam requested changes
Задачи решены, все в порядке.
У меня есть только несколько стилистических замечаний.

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/common/Helpers.java
> +    public static void checkDnaFast(final String dna) {
Не очень понятно зачем нужна эта проверка. По условиям задач входные данные предоставляются корректные. А проверка длины просто не для всех задач корректна.

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/common/Helpers.java
> +    public static <T> void executeStringInput(
Мне кажется, лучше назвать функцию и ее параметры более понятным образом:
```java
public static <T> void processAndPrintInputLine(
    Function<String, T> inputProcessor,
    Consumer<String> inputValidator,
    Function<T, String> outputConverter
) {...}
```

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/CountingDNANucleotide.java
> +                case 'A' -> map.merge('A', 1, Integer::sum);
Думаю что короче и понятнее было бы сначала сделать проверку, а потом уже складывать в map:
```java
private static final Set<Character> NUCLEOTIDES = Set.of('A', 'T', 'G', 'C');
...
for (int charIndex = 0; charIndex < data.length; charIndex++) {
    char upperCase = data.charAt(charIndex).toUpperCase();
    if (!NUCLEOTIDES.contains(upperCase)) {
        throw new IllegalArgumentException("Invalid symbol in data " + data.charAt(charIndex));
    }
    map.merge(upperCase, 1, Integer::sum);
}
```

Обратите также внимание, что здесь не создаются две копии исходной строки (которая может быть очень длинной), в отличие от Вашего решения.

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/CountingDNANucleotide.java
> +        return String.format("%d %d %d %d", map.getOrDefault('A', 0), map.getOrDefault('C', 0),
Это можно сделать например, так (не обязательно):
```java
return NUCLEOTIDES.stream()
    .map(c -> map.getOrDefault(c, 0))
    .map(Integer::toString)
    .collect(Collectors.joining());
```

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/DNAComplement.java
> +                .collect(StringBuilder::new,
Думаю что императивный подход с forEach был бы в данном случае короче и понятнее.

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/EnumeratingGeneOrders.java
> +        permutations.forEach(var -> System.out.println(var.stream()
Не стоит использовать `var` как имя переменной если Вы используете его как ключевое слово.

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/RnaToProteinTranslator.java
> +            String group = rnaUpper.substring(0, 3);
Для числа 3 лучше ввести именованную константу `CODON_LENGTH`

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/RnaToProteinTranslator.java
> +    private final static Map<CharSequence, Character> RNA_CODON_TABLE = new HashMap<>() {{
Думаю что вынести эти данные в текстовый файл было бы понятнее.
Но можете оставить как есть.

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/MotifInDna.java
> +        List<Integer> list = new ArrayList<>();
Лучше дать этой переменной более информативное имя, например `matchIndices`

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/EnumeratingKmersLexicographically.java
> +            enumerate(str.chars().mapToObj(c -> (char) c).filter(c -> c != ' ').collect(Collectors.toList()), n)
Лучше вынести аргумент метода `enumerate` в отдельную переменную.
Это лучше читается и удобнее при отладке.

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/EnumeratingTools.java
> +    public static <T> Set<List<T>> enumerate(final List<T> elements, int size) {
Может быть, лучше назвать `enumerateCombinations`

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/EnumeratingOrientedGeneOrderings.java
> +            result.forEach(var -> System.out.println(var.stream()
Здесь тоже лучше не называть переменную `var`

2021-02-15 09:19 UTC, dmitrii-adamian-at-epam commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/EnumeratingOrientedGeneOrderings.java
> +            for (int i = -1; i <= 1; i += 2) {
Цикл кажется переусложненным.
Может быть `for (int i : List.of(-1, 1))`?

2021-02-15 14:01 UTC, iporsh commented
Из пожеланий , код написан не очень хорошо читаемым т.к. вы старались сделать его более технологичным, Для решения текущих задач можно сделать так, но всетаки  старайтесь писать более просто. И второе пожелание старайтесь использовать не только static методы

2021-02-16 17:12 UTC, marsofandrew commented on andrey_petrov/src/com/marsofandrew/bioinformatic/common/Helpers.java
> +    public static void checkDnaFast(final String dna) {
ну про корректные данные я вероятно упустил

2021-02-16 17:17 UTC, marsofandrew commented on andrey_petrov/src/com/marsofandrew/bioinformatic/common/Helpers.java
> +    public static <T> void executeStringInput(
ну если у нас все входные параметры правильные, то обойдемся без валидатора, на этом этапе

2021-02-16 17:22 UTC, marsofandrew commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/CountingDNANucleotide.java
> +        return String.format("%d %d %d %d", map.getOrDefault('A', 0), map.getOrDefault('C', 0),
Да, чуть позже вспомнил про это, но код уже был написан.

2021-02-16 17:27 UTC, marsofandrew commented on andrey_petrov/src/com/marsofandrew/bioinformatic/tasks/RnaToProteinTranslator.java
> +    private final static Map<CharSequence, Character> RNA_CODON_TABLE = new HashMap<>() {{
Согласен, в виде json, но для задачи имеет мало смысла.

2021-02-16 17:35 UTC, marsofandrew commented
> Из пожеланий , код написан не очень хорошо читаемым т.к. вы старались сделать его более технологичным, Для решения текущих задач можно сделать так, но всетаки старайтесь писать более просто. И второе пожелание старайтесь использовать не только static методы

По поводу не static методов, тут не имело смысла, т.к. все задачи не требовали создания экземпляра класса, зачем?
Про простоту согласен.

2021-02-17 14:29 UTC, dmitrii-adamian-at-epam approved these changes
Зачтено, вливайте pull request, выбирайте проект или команду.

2021-02-17 16:03 UTC, merged