Resolve 10 tasks
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #12
Opened 2021-02-15 22:19 UTC by AleksandrStarovoitov

2021-02-16 08:33 UTC, Kirvolque commented on aleksandr_starovoitov/Model/FastaEntry.java
> +    private double gcContent;
Если есть возможность, всегда лучше делать поля `final`, а значения инициализировать через конструктор.

2021-02-16 08:33 UTC, Kirvolque commented on aleksandr_starovoitov/Utils/FileUtils.java
> +                fastaEntry.setDescription(sb.toString());
Здесь может быть один единственный вызов конструктора, инициализирующий все поля `fastaEntry` разом.
А значения полей `id` и `description` до этого момента хранить в локальных переменных.

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam requested changes
Задачи решены, но я нашел одну логическую ошибку и несколько стилистических моментов.
Исправляйте и запрашивайте ревью снова, думаю что это не должно занять у Вас много времени.

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/10_Enumerating_Kmers_Lexicographically/EnumeratingKmersLexicographically.java
> +        combination(str, count, new StringBuffer());
Используйте в большинстве случаев `StringBuilder` вместо `StringBuffer`.
`StringBuffer` использует синхронизацию для доступа из разных потоков, здесь Вам это не нужно

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/1_Counting_DNA_Nucleotides/CountingDNANucleotides.java
> +        var charCount = new HashMap<Character, Integer>();
Можно использовать Map.of():
```java
var charCounts = Map.of(
    'A', 0,
    'C', 0,
    'G', 0,
    'T', 0
);
```
но это необязательно.

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/5_Translating_RNA_into_Protein/TranslatingRNAintoProtein.java
> +        }
Здесь есть логическая ошибка - не обрабатывается стоп-кодон, он должен прекращать трансляцию строки.

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/5_Translating_RNA_into_Protein/TranslatingRNAintoProtein.java
> +        for (int i = 0; i < input.length() - 3; i = i + 3) {
Для числа 3 лучше завести именованную константу `CODON_LENGTH`

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/5_Translating_RNA_into_Protein/TranslatingRNAintoProtein.java
> +        table.put("UUU", 'F');
Возможно, лаконичнее было бы читать эти данные из текстового файла.
Но это необязательно.

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/8_Enumerating_Gene_Orders/EnumeratingGeneOrders.java
> +        var count = Integer.valueOf(input);
Эта локальная переменная скрывает статическое поле класса. Так лучше не делать, это ухудшает читаемость.

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/8_Enumerating_Gene_Orders/EnumeratingGeneOrders.java
> +        var numbers = Stream.iterate(1, n -> n + 1)
Может быть, проще использовать [IntStream.range(from, to)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/IntStream.html#range(int,int))?

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/Model/FastaEntry.java
> +        gcContent = (double)Math.round((double)(cCount + gCount) / description.length() * 100000000) / 1000000;
Насколько я понимаю, умножение и деление на большое число используется для вывода результата на печать. Лучше переместить эту операцию туда, где результат и выводится.
Сейчас понять что результат округлен можно только если читать код этого класса.

2021-02-16 08:48 UTC, dmitrii-adamian-at-epam commented on aleksandr_starovoitov/Utils/FileUtils.java
> +        var fullPath = Paths.get(FileUtils.class.getResource(fileName).getPath().substring(1));
Столько операций в одном выражении плохо читаются. Лучше создать переменную для аргумента Paths.get

2021-02-16 20:55 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/Model/FastaEntry.java
> +    private double gcContent;
Fixed in 4d174a81c1198da899f33329ce9041e4c61aa3cb

2021-02-16 20:55 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/Utils/FileUtils.java
> +                fastaEntry.setDescription(sb.toString());
Fixed in 4d174a81c1198da899f33329ce9041e4c61aa3cb

2021-02-16 20:56 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/10_Enumerating_Kmers_Lexicographically/EnumeratingKmersLexicographically.java
> +        combination(str, count, new StringBuffer());
Fixed in 262b371e9e849d3e63ebfbdbdf6b1fa99fd055be

2021-02-16 21:00 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/1_Counting_DNA_Nucleotides/CountingDNANucleotides.java
> +        var charCount = new HashMap<Character, Integer>();
Я так понимаю, что Map.of возвращает неизменяемый Map. В цикле вызывается `.put()`. Значит Map.of не получится использовать.
```
for (int i = 0; i < input.length(); i++) {
    ...
    charCount.put(c, currentCount + 1);
}
```

2021-02-16 21:00 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/5_Translating_RNA_into_Protein/TranslatingRNAintoProtein.java
> +        }
FIxed in 2e6a4888076db52efb3fda3cff58c96753d1acf8

2021-02-16 21:00 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/5_Translating_RNA_into_Protein/TranslatingRNAintoProtein.java
> +        for (int i = 0; i < input.length() - 3; i = i + 3) {
Fixed in 58eb85304672bc09f92f686931cba87fb1018ae0

2021-02-16 21:01 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/8_Enumerating_Gene_Orders/EnumeratingGeneOrders.java
> +        var count = Integer.valueOf(input);
Fixed in 7e1ca38f65af1df8942ae4f1016dc9d9cc854020

2021-02-16 21:03 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/8_Enumerating_Gene_Orders/EnumeratingGeneOrders.java
> +        var numbers = Stream.iterate(1, n -> n + 1)
Fixed in 3e6d35d34525ee1323f25c9866a5f1ab361a1352

2021-02-16 21:03 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/Model/FastaEntry.java
> +        gcContent = (double)Math.round((double)(cCount + gCount) / description.length() * 100000000) / 1000000;
Fixed in d445af3bb020d48bfd35d8662a3f8e52851b1ef0

2021-02-16 21:03 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/Utils/FileUtils.java
> +        var fullPath = Paths.get(FileUtils.class.getResource(fileName).getPath().substring(1));
Fixed in 6877cd0f5a7c7011b3dcc32e4970a42676675db3

2021-02-17 08:06 UTC, Kirvolque commented on aleksandr_starovoitov/1_Counting_DNA_Nucleotides/CountingDNANucleotides.java
> +        var charCount = new HashMap<Character, Integer>();
Можно использовать `new HashMap(Map.of(...))`

2021-02-17 08:46 UTC, AleksandrStarovoitov commented on aleksandr_starovoitov/1_Counting_DNA_Nucleotides/CountingDNANucleotides.java
> +        var charCount = new HashMap<Character, Integer>();
Fixed in f24a44877e1b7ecf3f502f2b003db050f41ca6a8

2021-02-17 14:24 UTC, dmitrii-adamian-at-epam approved these changes
Зачтено. Вливайте pull request, выбирайте проект или команду.

2021-02-17 19:43 UTC, merged