Add rosalind solutions
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #14
Opened 2021-02-19 14:54 UTC by oleg088097

Олег Кузьмин гр 3540904/00202
Проект: Motif discovery tool

2021-02-20 15:26 UTC, dmitrii-adamian-at-epam requested changes
Одна логическая ошибка и немного стилистических замечаний, в остальном все хорошо. Исправляйте проблему, запрашивайте ревью еще раз.

2021-02-20 15:26 UTC, dmitrii-adamian-at-epam commented on build.gradle.kts
> +}
Последнюю строчку нужно оставлять пустой. Автоматическое форматирование в IDE решает эту проблему

2021-02-20 15:26 UTC, dmitrii-adamian-at-epam commented on build.gradle.kts
> +    mavenCentral()
А Вам точно нужен тут gradle если Вы не используете зависимости?

2021-02-20 15:26 UTC, dmitrii-adamian-at-epam commented on src/main/kotlin/dna/main.kt
> +    println("${res['A'] ?: 0} ${res['C'] ?: 0} ${res['G'] ?: 0} ${res['T'] ?: 0}")
4 повторения одного выражения внутри string interpolation выглядят не очень читаемо.
Попробуйте использовать что-то вроде `listOf('A', 'T', 'G', 'C').map(...)`

2021-02-20 15:26 UTC, dmitrii-adamian-at-epam commented on src/main/kotlin/lcsm/main.kt
> +        .replace(Regex("\\s"), "")
Делать столько действие цепочкой вызовов не стоит. Это затрудняет отладку - сломается что-то и непонятно будет где. Ну и читаемость тоже не улучшает.

2021-02-20 15:26 UTC, dmitrii-adamian-at-epam commented on src/main/kotlin/prot/main.kt
> +    val res = s.chunked(3, { codons[it] }).joinToString("")
Здесь логическая ошибка. Стоп-кодон должен завершать трансляцию строки, а не просто игнорироваться.

2021-02-20 15:26 UTC, dmitrii-adamian-at-epam commented on src/main/kotlin/splc/main.kt
> +    val res = dna.replace("T".toRegex(), "U").chunked(3, { codons[it] }).joinToString("")
Та же проблема что и выше - неправильно обрабатывается стоп-кодон.

2021-02-20 15:26 UTC, dmitrii-adamian-at-epam commented
И конфликт в .gitignore почините, пожалуйста.

2021-02-20 15:34 UTC, oleg088097 commented on build.gradle.kts
> +}
Да я и не сам его писал?) Что нагенерила Идея, то выложились) Поправлю

2021-02-20 15:36 UTC, oleg088097 commented on build.gradle.kts
> +    mavenCentral()
В целом - нет. Но хуже от него точно не будет в любом проекте, авось захочется чего добавить или собирать исполняемый jar

2021-02-20 15:37 UTC, oleg088097 commented on src/main/kotlin/prot/main.kt
> +    val res = s.chunked(3, { codons[it] }).joinToString("")
В случае с корректными данными, на которые всё и рассчитано, он будет последним, разве нет?

2021-02-20 16:04 UTC, dmitrii-adamian-at-epam commented on src/main/kotlin/prot/main.kt
> +    val res = s.chunked(3, { codons[it] }).joinToString("")
Нет, это не так. Т.е. я не помню про конкретно эту задачу, но вообще-то трансляция всегда заканчивается по стоп-кодону, настоящие матричные РНК заканчиваются [поли-А хвостом](https://ru.wikipedia.org/wiki/Полиаденилирование) у эукариот (т.е. всех кроме бактерий и некоторых других одноклеточных).

2021-02-22 13:49 UTC, dmitrii-adamian-at-epam approved these changes

2021-03-10 07:27 UTC, merged