Solved 10 tasks
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #15
Opened 2021-02-23 04:10 UTC by Prokhorovmax

0: DNA  - Counting DNA Nucleotides
1: RNA  - Transcribing DNA into RNA
2: REVC - Complementing a Strand of DNA
3: FIB  - Rabbits and Recurrence Relations
4: FIBD - Mortal Fibonacci Rabbits
5: GC   - Computing GC Content
6: PROT - Translating RNA into Protein
7: SUBS - Finding a Motif in DNA
8: HAMM - Counting Point Mutations
9: REVP - Locating Restriction Sites

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam requested changes
Несколько стилистических замечаний, в остальном все в порядке.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/.gitkeep
> -
Не удаляйте чужой файл

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Main.java
> +                        System.out.println(Tasks.countingDNANucleotides(getString(fileName)));
Это выражение повторяется, имеет смысл вынести switch в отдельный метод:
```java
private static String dispatchTaskByIndex(int taskNumber) {
    String fileName;
    switch (taskNumber) {
        case 0:
            fileName = ...
            return Tasks.countingDNANucleotides(getString(fileName));
    }
}

main() {
    ...
    int taskNumber = Integer.parseInt(args[0]);
    String result = dispatchTaskByIndex(taskNumber);
    System.out.println(result);
}
```

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Main.java
> +        BufferedReader fileReader = new BufferedReader(new FileReader(fileName));
Здесь файл не закрывается, используйте try-with-resources.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Main.java
> +        while ((str = fileReader.readLine()) != null) {
Можно использовать [Files.readAllLines()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Files.html#readAllLines(java.nio.file.Path)) тогда код станет сильно проще.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Main.java
> +            if (str.charAt(0) != '>')
Лучше ставить фигурные скобки даже для одного выражения - это улучшает читаемость и снижает вероятность ошибок.
Например, [Google Code Style](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used) рекомендует так делать.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +                case 'A': {
switch тоже обычно оформляют по другому: [Google Code Style](https://google.github.io/styleguide/javaguide.html#s4.8.4-switch)

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +        int A_count = 0;
Решение с Map<String, Integer> будет гораздо компактнее.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +            switch (dataset.charAt(dataset.length() - i - 1)) {
Содержимое скобок switch лучше вынести в отдельную переменную - это улучшит читаемость.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +            else result.add(result.get(i - 1) + result.get(i - 2) * k);
Здесь тоже лучше добавить фигурные скобки и разбить на строки -  будет лучше читаться.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +            else result.add(result.get(i - 1) + result.get(i - 2) - result.get(i - m - 1));
То же самое что и выше - слишком много действий происходит в каждой строке, нужно разбить на части.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +                bestContentName = str.substring(1, 14);
А что означает константа 14? Если что-то осмысленное - то для нее лучше сделать именованную константу.

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +        for (char ch : string.toCharArray())
String.toCharArray() создает копию массива. Здесь это не очень важно, но если входная строка очень большая - то потребление памяти может увеличиться вдвое.
Лучше использовать `String.charAt(i)`

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +        for (int i = 0; i < dataset.length(); i += 3) {
Для числа 3 лучше создать именованную константу `CODON_LENGTH`

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +            if (string.substring(i, i + seqLength).equals(seq)) result.append(i + 1).append(" ");
Здесь точно слишком много всего происходит в одной строчке - плохо читается

2021-02-26 16:21 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +            int endIndex = (i < datasetLength - 12) ? 13 : (datasetLength - i + 1);
Тоже непонятно что означают числа 12 и 13. Сделайте для них, пожалуйста, именованные переменные или константы.

2021-02-27 00:59 UTC, Prokhorovmax commented on maksim_prokhorov/src/Main.java
> +        while ((str = fileReader.readLine()) != null) {
К сожалению, логика несколько сложнее чем просто достать список строк. Мне нужно выполнить слияние строк под одним именем, и мне кажется, что выгоднее это делать сразу в цикле, чем потом редактировать список.
Остальное исправил.

2021-03-02 09:42 UTC, dmitrii-adamian-at-epam reviewed
Два из старых комментариев не поправил, я еще один добавил, но это не обязательно исправлять.

2021-03-02 09:42 UTC, dmitrii-adamian-at-epam commented on maksim_prokhorov/src/Tasks.java
> +            switch (ch) {
Здесь можно вообще обойтись без switch:
```java
for (int i = 0; i < dataset.length(); i++) {
    char ch = dataset.charAt(i);
    if (!count.contains(ch)) {
        return "Wrong input line.";
    }
    count.merge(ch, 1, Integer::sum);
}
```

2021-03-04 15:56 UTC, dmitrii-adamian-at-epam approved these changes

2021-03-05 11:53 UTC, merged