Add solutions by Aleksandra Popova
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #18
Opened 2021-02-25 20:08 UTC by Vooxi

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam requested changes
Замечания у меня только стилистические, но достаточно существенные.
Поправьте, пожалуйста.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/10_Translating_RNA_into_Protein/Main.java
> +		Reader inputStreamReader = new InputStreamReader(System.in);
Используйте [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) здесь и в остальных задачах.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/10_Translating_RNA_into_Protein/Main.java
> +}
Последняя строка должна быть пустой. Автоматическое форматирование кода в IDE решает эту проблему.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/10_Translating_RNA_into_Protein/Main.java
> +		HashMap<String, String> table = getCodonTable();
Обычно тип коллекции определяют интерфейсом (List, Map,...), а не конкретным классом реализации. Это помогает читаемости (меньше разных типов) и более единообразно при использовании List.of(), Collections.synchronizedMap() и тд.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/10_Translating_RNA_into_Protein/Main.java
> +		for (int i = 0; i < s.length(); i += 3) {
Для числа 3 лучше использовать именованную константу `CODON_LENGTH`.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/1_Calculating_Protein_Mass/Main.java
> +        HashMap<Character, Double> MassTable = new HashMap<>();
Переменные принято называть с маленькой буквы.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/1_Calculating_Protein_Mass/Main.java
> +        char[] cArray = c.toCharArray();
Операция [String.toCharArray()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#toCharArray()) создает копию содержимого строки. Здесь это не очень важно, но для больших строк это увеличивает потребление памяти вдвое. В этом случае лучше использовать `String.charAt(index)`.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/2_Counting_DNA_Nucleotides/Main.java
> +            else{
Нет пробела перед фигурной скобкой. Попробуйте настроить автоматическое форматирование кода.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/2_Counting_DNA_Nucleotides/Main.java
> +        int countA = 0;
Так сделать можно, но это приводит к длинному `if`. Попробуйте сделать более лаконичное решение с массивом или Map.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/4_Counting_Subsets/Main.java
> +package com.company;
Бессмысленные названия пакетов лучше не использовать - это только ухудшает читаемость. Можно переименовать в `ru.spbstu.coursework` например

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/6_Transcribing_DNA_into_RNA/Main.java
> +        for (int i = 0; i < cArray.length; i++){
Это можно сделать при помощи String.replace().

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/8_Complementing_a_Strand_of_DNA/Main.java
> +		HashMap<Character, Character> map = new HashMap<Character, Character>(Map.of(
Нет никакой необходимости оборачивать этот Map в новый HashMap, можно просто сменить тип переменной `map` на `Map<Character, Character>`.

2021-03-02 08:51 UTC, dmitrii-adamian-at-epam commented on aleksandra_popova/9_Finding_a_Motif_In_DNA/Main.java
> +				positions.add(++index);
Это выражение лучше разбить на два, так как в нем происходят два различных изменения состояния. Если в каждой строке может измениться состояние только одной переменной, то читать код проще.

2021-03-02 19:08 UTC, Vooxi commented
Поправила, посмотрите пожалуйста

2021-03-04 16:01 UTC, dmitrii-adamian-at-epam approved these changes

2021-03-10 07:27 UTC, merged