Chernov denis
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #26
Opened 2021-03-04 12:25 UTC by deloboiden

complete 10 labs

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam requested changes
Задачи решены верно, но есть несколько замечаний, требующих исправления:
* Не закрываются потоки чтения
* Имена методов с большой буквы
* Нужно проследить за форматированием кода - это важно для читаемости кода при работе в команде. Попробуйте использовать автоматическое форматирование.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/SUBS/Main.java
> +}
Последнюю строку файла принято оставлять пустой (если она не пустая - это отображается при просмотре pull request на github).
Автоматическое форматирование кода решает эту проблему.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/RNA/Main.java
> +        FileInputStream fileInputStream = new FileInputStream("src/RNA/rosalind_rna.txt");
Stream здесь не закрывается должным образом.
Здесь проще использовать Files.readAllLines(). Если хочется именно Stream - нужно оборачивать в try-with-resources.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/RECV/Main.java
> +        FileInputStream fileInputStream = new FileInputStream("src/RECV/rosalind_revc.txt");
Здесь тоже не закрывается Stream.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/PROT/Main.java
> +        for (int i = 0; i < rna.length()-3; i+=3){
Для числа 3 лучше создать именованную константу `CODON_LENGTH`.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/PROT/Main.java
> +            if (result.equals("Stop"))
[Google Java Code Style](https://google.github.io/styleguide/javaguide.html#s4.1-braces) рекомендует ставить фигурную скобку даже если в блоке 1 выражение. Это снижает вероятность ошибки если этот блок будет впоследствии изменяться.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/PROT/Main.java
> +                System.out.println();
Стоп-кодон должен завершать трансляцию РНК, цикл должен прерываться.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/IPRB/Main.java
> +        catch (Exception e){
В Java блоки кода принято оформлять так: https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style
`catch` должен быть на той же строке, что и закрывающая скобка try.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/DNA/Main.java
> +        FileInputStream fileInputStream = new FileInputStream("src/DNA/rosalind_dna(1).txt");
Здесь тоже не закрывается Stream

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/CONS/Main.java
> +    public static HashMap<String, String> ReadFASTA(String path) throws IOException {
* Названия методов принято начинать с маленькой буквы
* Для возвращаемого типа лучше использовать более общий интерфейс `Map<String, String>` - это делает кол более единообразным при использовании `TreeMap` или `Map.of()`

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/CONS/Main.java
> +            for (int i = 0; i < 4; i ++){
Для числа 4 тоже лучше создать именованную константу.
А лучше сделать константу - массив всех нуклеотидов и обойтись без switch ниже.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/CONS/Main.java
> +        while (iter.hasNext()){
Можно написать проще:
```java
Collection<String> sequences = readFasta(...).values();
int sequenceLength = sequences.iterator().next().length();
int[][] matrix = new int[sequenceLength][4];
for (String dna: sequences) {
    ...
}

```

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/GC/Main.java
> +    public static double CalculateCGcontent(List<String> sequence){
Здесь тоже нужно начинать имя метода с маленькой буквы.

2021-03-10 16:15 UTC, dmitrii-adamian-at-epam commented on chernov_denis/GC/Main.java
> +        double squenceLength = 0;
* Орфографическая ошибка - `sequenceLength`, а не `squenceLength`.
* Можно использовать int/long (не обязательно)

2021-03-10 17:02 UTC, deloboiden commented
Исправил все замечания.

2021-03-11 13:10 UTC, dmitrii-adamian-at-epam approved these changes
Зачтено, вливайте ветку.

2021-03-11 13:10 UTC, dmitrii-adamian-at-epam commented on chernov_denis/CONS/Main.java
> +    static final Character[] NUKLEOTIDES = {'A', 'C', 'G', 'T'};
`NUCLEOTIDES`

2021-03-22 06:25 UTC, merged