Sophia Chernousova
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #27
Opened 2021-03-05 14:03 UTC by sophiacrumb

Completed all 10 tasks

2021-03-05 14:15 UTC, sophiacrumb commented
@dmitrii-adamian-at-epam Добрый день. Проведите ревью, пожалуйста :)

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam requested changes
Задачи решены, но в одной решение имеет слишком большую алгоритмическую сложность. Также у меня есть несколько стилистических замечаний.

Обратите внимание на форматирование кода. При работе в команде важно придерживаться единого стиля, без этого чтение кода будет затруднено.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on DNA.java
> +		for (char c: dataSet.toCharArray())
* [Google Java Code Style](https://google.github.io/styleguide/javaguide.html#s4.1-braces) рекомендует ставить фигурные скобки даже если только одно выражение в теле цикла.
* String.toCharArray() копирует содержимое строки, что может вдвое увеличить потребление памяти для большой строки.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on DNA.java
> +			map.put(c, map.getOrDefault(c, 0) + 1);
```java
map.merge(c, 1, Integer::sum);
```

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on FIB.java
> +				children = (parents * rabbitsProductivity) + pairsNumber;
Отступы в Вашем коде длиннее чем обычно используются. Это не проблема если Вы пишете только для себя, но в команде лучше иметь единый стиль кода - лучше читается. Попробуйте автоматическое форматирование кода.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on FIB.java
> +		if (months == 1 || months == 2)
Здесь тоже не хватает скобок.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on HAMM.java
> +		{
В Java принято ставить открывающую скобку в конец предыдущей строки.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on PERM.java
> +		    for (int i = 0; i < n; i++) {
Здесь форматирование кода точно поломалось и не соответствует реальному уровню вложенности.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on PROT.java
> +			var aminoAcid = table.get(dataSet.substring(i, i + codonLength));
Лучше не делать много операций в одной строке - это затрудняет чтение и отладку. Можно вынести `dataset.substring()` в переменную `codon`.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on PRTM.java
> +		{
Здесь тоже неправильно расположены скобки.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on REVC.java
> +				complimentDNAString += 'T';
Алгоритмическая сложность Вашего решения - O(N^2), где N - длина строки.
В Java для формирования строк нужно использовать StringBuilder.

Также цепочку if-else можно заменить на поиск комплементарного символа в константном массиве:
```java
var complements = Map.of(
    'A', 'T',
    'T', 'A',
    'G', 'C',
    'C', 'G'
);
```

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on Utils.java
> +        return Files.readAllLines(Paths.get(Utils.class.getResource(fileName).getPath().substring(1)));
Эту строку нужно разбить на несколько, в ней слишком много всего происходит.

2021-03-10 15:51 UTC, dmitrii-adamian-at-epam commented on SUBS.java
> +		ArrayList<Integer> indexes = new ArrayList<>();
Здесь можно использовать аннотацию типа `List<Integer>` или просто var.
Использовать List лучше, чем ArrayList, так как это более единообразно с `List.of()`.

2021-03-10 22:33 UTC, limnin requested changes

2021-03-10 22:33 UTC, limnin commented on FIB.java
> +		int months = Integer.parseInt(dataSet.split(" ")[0]);
`dataSet.split(" ")` хорошо бы вынести в отдельную переменную

2021-03-10 22:33 UTC, limnin commented on FIB.java
> +		long pairsNumber = 1;
определяем количество пар, а потом через две строчки переопределяем, выглядит запутывающе

2021-03-10 22:33 UTC, limnin commented on IPRB.java
> +		int k = Integer.parseInt(dataSet.split(" ")[0]);
И снова `dataSet.split(" ")` хорошо бы вынести в отдельную переменную

2021-03-10 22:33 UTC, limnin commented on PERM.java
> +		if (num <= 1)
я правильно понимаю, что мы тут факториал рекурсивно считаем? мне кажется, циклом это намного понятнее.

2021-03-10 22:33 UTC, limnin commented on PERM.java
> +	{
мне кажется, лучше соблюдать единый стиль расстановки скобок, в Java обычно открывающая скобка ставится на той же строке, а не переносится на следующую.

2021-03-10 22:33 UTC, limnin commented on PERM.java
> +			for (int i = 0; i < array.length; i++)
Даже одиночные операторы в теле циклов, условий и так далее лучше выделять в блок фигурными скобками, улучшает читаемость

2021-03-10 22:33 UTC, limnin commented on PROT.java
> +	static {
такие длинные блоки инициализации очень затрудняют чтение кода; стоит, например, вынести в отдельный файл .properties и при помощи  java.util.Properties его прочитать.

2021-03-10 22:33 UTC, limnin commented on REVC.java
> +			if (reversedString.charAt(i) == 'A') {
культурнее составить короткую мапу соответствий и сразу доставать комплементарное значение оттуда, что сразу сэкономит много развесистых if-else

2021-03-10 22:33 UTC, limnin commented on SUBS.java
> +		int index = 0;
место этому объявлению переменной - внутри ветки else

2021-03-15 15:51 UTC, dmitrii-adamian-at-epam approved these changes
Зачтено, вливайте ветку.

2021-03-17 08:14 UTC, merged