resolve tasks
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #28
Opened 2021-03-10 22:07 UTC by maskindmitriy

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam requested changes
Задачи решены, но в двух местах алгоритмическая сложность решения выше оптимальной. Также есть несколько стилистических замечаний.

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/10_TRAN/TRAN.java
> +        String str1 = Utils.readFromFile(FILE_PATH).get(0);
* Метод Utils.readFromFile отсутствует в пулл реквесте.
* Лучше обойтись без чтения дважды - можно создать переменную для результата вызова Utils.readFromFile()

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/10_TRAN/TRAN.java
> +            if (s1.charAt(i) == 'A' && s2.charAt(i) == 'G' || s1.charAt(i) == 'G' && s2.charAt(i) == 'A')
* [Google Java Code Style](https://google.github.io/styleguide/javaguide.html#s4.1-braces) рекомендует ставить фигурные скобки даже если в теле if/for только одно выражение. Это снижает возможность ошибки при изменении кода
* Можно написать с меньшим количеством повторений кода (не обязательно):
```java
Set<Set<Character>> transitionsSet = Set.of(
    Set.of('A', 'G'), Set.of('G', 'A'), Set.of('C', 'T'), Set.of('T', 'C')
);
Set<Set<Character>> transversionsSet = Set.of(
    Set.of('A', 'C'), Set.of('C', 'A'), Set.of('G', 'T'), Set.of('T', 'G')
);
for (int i = 0; i < s1.length(); i++) {
    char c1 = s1.charAt(i);
    char c2 = s2.charAt(i);
    if (transitionsSet.contains(Set.of(c1, c2)) {
        transitions++;
    } else if (transversionsSet.contains(Set.of(c1, c2)) {
        transversions++;
    }
    if (c1 != c2) {
        diff++;
    }
}
```

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/1_DNA/DNA.java
> +        for (int i = 0; i < s.length(); i++) {
Можно написать короче с двойным циклом:
```java
char[] nucleotides = new char[] {'A', 'C', 'G', 'T'};
int[] counts = new int[nucleotides.length];

for (int i = 0; i < s.length(); i++) {
    for (int j = 0; j < nucleotides.length; j++) {
        if (s.charAt(i) == nucleotides[j]) {
            counts[j]++;
        }
    }
}
```

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/8_RNA/RNA.java
> +    public static String transcrib(String s) {
`transcribe` или `transcription`

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/7_REVC/REVC.java
> +                res += 'T';
Алгоритмическая сложность этого решения - O(N^2) где N - длина строки. Используйте StringBuilder для составления строки.

Также можно убрать цепочку одинаковых if, а вместо этого использовать массив нуклеотидов.

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/3_LCSM/LCSM.java
> +        String commonStr="";
Используйте автоматическое форматирование кода для единообразия.

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/3_LCSM/LCSM.java
> +                            break;
Здесь 5 уровней вложенности. Это ухудшает читаемость. Можно как-то сократить? Может быть что-то вынести в отдельный метод, например.

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/5_PROT/PROT.java
> +        for (int i = 0; i < s.length() - 3; i += 3) {
Для числа 3 лучше создать именованную константу `CODON_LENGTH`

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/5_PROT/PROT.java
> +        String aminoSeqence = "";
Орфографическая ошибка, должно быть `aminoSequence`.

2021-03-11 13:45 UTC, dmitrii-adamian-at-epam commented on dmitriy_maskin/src/5_PROT/PROT.java
> +                    aminoSeqence += entry.getValue();
Здесь тоже алгоритмическая сложность квадратичная относительно длины строки.

2021-03-13 01:05 UTC, maskindmitriy commented on dmitriy_maskin/src/5_PROT/PROT.java
> +        String aminoSeqence = "";
Однократная опечатка и автозамена

2021-03-13 01:37 UTC, merged