add 10 tasks
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #29
Opened 2021-03-12 20:26 UTC by AstralRomance

2021-03-24 15:18 UTC, dmitrii-adamian-at-epam requested changes
Уберите, пожалуйста, содержимое /venv из пулл-реквеста. Такой огромный PR невозможно читать.
Также задание нужно было сделать на Java, поскольку проекты тоже на ней.

2021-04-11 14:56 UTC, AstralRomance commented
Убрал venv, не заметил, что ее не было в игноре.
Раз можно сделать индивидуальный проект, его же можно делать на питоне?

2021-04-13 12:03 UTC, dmitrii-adamian-at-epam commented
Да, можно индивидуальный проект делать на питоне.

2021-04-13 12:04 UTC, dmitrii-adamian-at-epam approved these changes

2021-04-22 10:22 UTC, merged