Aslan aghayev
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #35
Opened 2021-03-22 17:00 UTC by agaevaslan

2021-03-26 16:15 UTC, dmitrii-adamian-at-epam requested changes
Два решения имеют неоптимальную алгоритмическую сложность, также у меня есть несколько стилистических замечаний.
После исправления (в этом pull request, не надо создавать новый) запрашивайте ревью еще раз.

2021-03-26 16:15 UTC, dmitrii-adamian-at-epam commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +    println("Hello World!")
Это не относится к решению.

2021-03-26 16:15 UTC, dmitrii-adamian-at-epam commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +        println(al + ' ' + s.count { al.contains(it) })
Это решение читает строчку (потенциально большую) целых 8 раз.
Попробуйте использовать только одно прочтение.

2021-03-26 16:15 UTC, dmitrii-adamian-at-epam commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +        res += when (s[i]) {
Это решение имеет алгоритмическую сложность O(N^2) относительно длины строки. Операция `+=` для строк копирует всю строку каждый раз.

2021-03-26 16:15 UTC, dmitrii-adamian-at-epam commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +    for (i in 3..s.length step 3) {
Для числа 3 лучше завести константу `CODON_LENGTH`.

2021-03-26 16:15 UTC, dmitrii-adamian-at-epam commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +            res += new;
Здесь тоже квадратичная сложность решения.

2021-03-26 16:15 UTC, dmitrii-adamian-at-epam commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +    var resCount = 0.00000
А зачем столько нулей?

2021-04-02 13:01 UTC, agaevaslan commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +        println(al + ' ' + s.count { al.contains(it) })
исправил

2021-04-02 13:01 UTC, agaevaslan commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +        res += when (s[i]) {
исправил

2021-04-02 13:03 UTC, agaevaslan commented on Aslan_Aghayev/src/main/kotlin/main.kt
> +    var resCount = 0.00000
Не помню, но могу предположить, что не сходился ответ и я решил проверить, влияет ли в котлин количество нулей на точность вычислений ( :))))) ) , а потом не вернул обратно

2021-04-02 13:27 UTC, dmitrii-adamian-at-epam approved these changes

2021-04-05 17:49 UTC, merged