Add solutions for 10 tasks from Rosalind
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #4
Opened 2021-02-04 23:16 UTC by hoklet

Добавил решения 10 задач из Rosalind:

1. Counting DNA Nucleotides 
2. Transcribing DNA into RNA 
3. Complementing a Strand of DNA 
4. Rabbits and Recurrence Relations 
5. Computing GC Content 
6. Counting Point Mutations 
7. Mendel's First Law 
8. Translating RNA into Protein 
9. Finding a Motif in DNA 
10. Calculating Protein Mass

Все в отдельных main-иках так удобнее было запускать, чтобы заливать решения на Rosalind.

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam requested changes
У меня несколько стилистических замечаний, в остальном все хорошо.

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam commented on Igor_Konev/CalculatingProteinMass.java
> +    static {
Блоки инициализации лучше не использовать без явной необходимости. Это плохо читается и считается плохим стилем в Java.
На мой взгляд лучше использовать метод [Map.ofEntries()](https://docs.oracle.com/javase/9/docs/api/java/util/Map.html#ofEntries-java.util.Map.Entry...-)

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam commented on Igor_Konev/DatasetReader.java
> +        final StringBuilder resultStringBuilder = new StringBuilder();
Здесь можно использовать [Files.readAllBytes()](https://docs.oracle.com/javase/9/docs/api/java/nio/file/Files.html#readAllBytes-java.nio.file.Path-) или [Files.readAllLines()](https://docs.oracle.com/javase/9/docs/api/java/nio/file/Files.html#readAllLines-java.nio.file.Path-)

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam commented on Igor_Konev/CalculatingProteinMass.java
> +        } catch (FileNotFoundException e) {
В таких маленьких программках можно не ловить исключения вообще, просто добавить `throws Exception` в сигнатуру. Так даже понятнее, поскольку `e.getMessage()` часто не дает важных деталей.

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam commented on Igor_Konev/CalculatingProteinMass.java
> +            proteinMass += monoisotopicMass.getOrDefault(protein.charAt(i), 0.0);
Это можно сделать короче:
```java
return protein.chars()
    .mapToDouble(c -> monoisotopicMass.getOrDefault(c, 0.0))
    .collect(Collectors.summingDouble());
```

Впрочем, это дело вкуса скорее.

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam commented on Igor_Konev/ComplementingStrandOfDNA.java
> +        final StringBuilder reversedSymbols = new StringBuilder();
Здесь тоже можно сильно короче написать:
```java
Map<Char, Char> complements = Map.of(
    'A', 'T',
    'C', 'G,
    'G', 'C',
    'T', 'A'
);
StringBuilder result = new StringBuilder();
dna.chars().foreach(c -> result.append(complement.getOrDefault(c, c));
return result.reverse().toString();
```

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam commented on Igor_Konev/ComputingGCContent.java
> +class Tuple<K, V> {
Этот класс используется только для того чтобы вернуть два значения и сразу вывести их на печать.
Может быть стоит сразу их печатать, тогда и `Tuple` не понадобится.

Кроме того, в Java обычно принято делать классы с конкретными названиями, например `SeqIdWithGCContent`. Tuple все-таки лучше использовать только в тех языках, где есть их поддержка прямо в языке.

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam commented on Igor_Konev/CountingDNANucleotide.java
> +                    nucleotides.merge("A", 1, Integer::sum);
Здесь точно можно сильно упростить себе жизнь если сделать так:
```java
Map<Character, Long> nucleotides = str.toUpperCase()
    .chars()
    .collect(Collectors.groupingBy(
        Functions.identity(),
        Collectors.counting()
    );
```

2021-02-05 12:53 UTC, dmitrii-adamian-at-epam commented on Igor_Konev/MendelsFirstLaw.java
> +        try (Scanner s = new Scanner(new FileReader("/tmp/rosalind_iprb.txt"))) {
У Вас постоянно используется блок `try(Scanner s = ...) {...} catch(...){..}`. 
Его можно вынести в функцию и переиспользовать в разных классах.
```java
public static withFile(String filePath, Consumer<Scanner> scannerConsumer) {
    try (Scanner s = new Scanner(new FileReader(filePath))) {
        scannerConsumer.accept(s);
    } catch (FileNotFoundException e) {
        ...
    }
}

public static void main(String [] args) {
    withFile("/tmp/rosalind_iprb.txt", s -> {
        double dominant = s.nextDouble();
        ...
    })
}
```

2021-02-05 13:09 UTC, limnin reviewed
Good job!

2021-02-05 13:09 UTC, limnin commented on Igor_Konev/CalculatingProteinMass.java
> +public class CalculatingProteinMass {
Маленькое замечание: хорошее название класса - это существительное. Что-нибудь вроде ProteinMassCalculator, так же относится к нескольким классам ниже.

2021-02-05 13:09 UTC, limnin commented on Igor_Konev/ComplementingStrandOfDNA.java
> +            switch (dna.charAt(i)) {
маленький, явно заданный map - и код станет сильно короче.

2021-02-05 13:09 UTC, limnin commented on Igor_Konev/ComputingGCContent.java
> +            }
Насколько я понимаю, решение несколько избыточно, т.к. нам нужно всего лишь отсечь ID и затем посчитать в остатавшемся куске строки количество G и С, таким образом, на субтокены делить, а потом по ним итерироваться, необязательно, верно?

2021-02-05 13:09 UTC, limnin commented on Igor_Konev/CountingDNANucleotide.java
> +            switch (upperStr.charAt(i)) {
копипаста, которой, как и оператора switch, можно избежать, существенно сократив код

2021-02-05 13:09 UTC, limnin commented on Igor_Konev/MendelsFirstLaw.java
> +        final double twoHetero = (1.0/4.0) * ((m/sum) * ((m - 1)/(sum - 1)));
Микрозамечание:
(1.0/4.0) = 0.25
Если сделано для явной читаемости формулы, возможно, лучше записать как 1.0/2 * 1.0/2 или 0.5*0.5, хотя в данном случае я бы читаемостью пренебрег, и так ясно откуда 0.25.

2021-02-05 13:09 UTC, limnin commented on Igor_Konev/RabbitsAndRecurrenceRelations.java
> +    public static long countRabbitPairs(final int n, final int k) {
параметрам n и k какие-нибудь self-describing имена бы

2021-02-05 13:09 UTC, limnin commented on Igor_Konev/TranslatingRNAIntoProtein.java
> +            while ((br.read(codon, 0, 3)) != -1) {
Я бы сказал, что на всякий случай, лучше проверять, а смогли ли мы прочитать ровно три символа, нежели проверять, что именно сейчас произошел конец файла, но работать будет и так, конечно.
Еще не очень хорошая практика с точки зрения читаемости кода использовать управление выходом из цикла посредством break (при разрастании логики становится трудно понять условие выхода из цикла, когда оно размазано по нескольким местам), но в данном случае, на мой взгляд, делу не мешает.

2021-02-08 18:21 UTC, hoklet commented on Igor_Konev/CalculatingProteinMass.java
> +public class CalculatingProteinMass {
Парирую. Здесь названия классов совпадают с названиями задач на Rosalind как раз для того, чтобы проверяющим было понятнее, что это за задача. 
Если бы классы использовались где-то вне этого, то назвал бы их соответствующе

2021-02-08 18:22 UTC, hoklet commented on Igor_Konev/ComplementingStrandOfDNA.java
> +            switch (dna.charAt(i)) {
Исправлено

2021-02-08 18:29 UTC, hoklet commented on Igor_Konev/ComputingGCContent.java
> +            }
Если мы заранее знаем, что все ID будут одинаковой длины и формата, то да, изыбочно. Можно захардкодить. Я же решил, что мы этого не знаем, поэтому просто сплитим по \n. Но в файле, взятом из Rosalind, DNA располагается на нескольких строчках, а не одной строкой. Поэтому при сплите DNA тоже разбивается на несколько частей. По ним и итерируюсь

2021-02-08 18:29 UTC, hoklet commented on Igor_Konev/CountingDNANucleotide.java
> +            switch (upperStr.charAt(i)) {
Исправлено

2021-02-08 18:30 UTC, hoklet commented on Igor_Konev/MendelsFirstLaw.java
> +        final double twoHetero = (1.0/4.0) * ((m/sum) * ((m - 1)/(sum - 1)));
Согласен, заменил на явные коэффициенты

2021-02-08 18:32 UTC, hoklet commented on Igor_Konev/RabbitsAndRecurrenceRelations.java
> +    public static long countRabbitPairs(final int n, final int k) {
Исправлено

2021-02-08 18:38 UTC, hoklet commented on Igor_Konev/TranslatingRNAIntoProtein.java
> +            while ((br.read(codon, 0, 3)) != -1) {
Исправил проверку на чтение ровно 3х символов. 
На счет break согласен, но в данном случае оставлю как есть, т.к. попытки зарефакторить код, чтобы было без него, приводят к еще меньшей читаемости.

2021-02-08 18:38 UTC, hoklet commented on Igor_Konev/CalculatingProteinMass.java
> +    static {
Переделал на `Map.ofEntries()`

2021-02-08 18:39 UTC, hoklet commented on Igor_Konev/CalculatingProteinMass.java
> +        } catch (FileNotFoundException e) {
Согласен, исправил

2021-02-08 18:39 UTC, hoklet commented on Igor_Konev/CalculatingProteinMass.java
> +            proteinMass += monoisotopicMass.getOrDefault(protein.charAt(i), 0.0);
Исправлено

2021-02-08 18:39 UTC, hoklet commented on Igor_Konev/ComplementingStrandOfDNA.java
> +        final StringBuilder reversedSymbols = new StringBuilder();
Исправлено

2021-02-08 18:39 UTC, hoklet commented on Igor_Konev/ComputingGCContent.java
> +class Tuple<K, V> {
Удалил Tuple. Заменил на просто печать нужной информации в методе

2021-02-08 18:40 UTC, hoklet commented on Igor_Konev/CountingDNANucleotide.java
> +                    nucleotides.merge("A", 1, Integer::sum);
Исправлено

2021-02-08 18:41 UTC, hoklet commented on Igor_Konev/MendelsFirstLaw.java
> +        try (Scanner s = new Scanner(new FileReader("/tmp/rosalind_iprb.txt"))) {
Согласен, если бы оставил `catch`, то так бы и сделал. Но из-за комментария выше удалил все `catch`, переделав на `throws`. А засовывать один `try with resources` в отдельный метод - избыточно

2021-02-08 19:02 UTC, hoklet commented on Igor_Konev/DatasetReader.java
> +        final StringBuilder resultStringBuilder = new StringBuilder();
Переделал на `Files.readAllLines()`

2021-02-09 15:32 UTC, dmitrii-adamian-at-epam approved these changes

2021-02-11 08:59 UTC, dmitrii-adamian-at-epam commented
@hoklet  выбирайте проект.

2021-02-25 18:04 UTC, merged