Add solutions of 10 tasks
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #6
Opened 2021-02-06 21:48 UTC by o-sokolova

2021-02-08 19:23 UTC, Cjkjvfnby requested changes
Глянул на задачу 1

2021-02-08 19:23 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Main.java
> +            ex.printStackTrace();
В случае именно этой ошибки мне часто трейсбэк не интересен. Давай попробуем вывести сообщение которое будет понятно человеку, даже если оне не программист.    

Добавь пожулуйста пример вывода в коментарий к сообщению.

2021-02-08 19:23 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Main.java
> +        return listOfLines;
Можно сделать inline этой переменной. Код будет короче и не потеряет в читаемости.

 Случайный пример из интернета https://www.jetbrains.com/help/resharper/Refactorings__Inline_Variable.html

2021-02-08 19:23 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        Map<String, Long> map = Arrays.stream(str.split("")).collect(Collectors.groupingBy(s -> s, Collectors.counting()));
Можно ли упростить этот код?  `Arrays.stream(str.split(""))`?

2021-02-08 19:23 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        List<Long> counts = new ArrayList<>();
Есть два подхода: стиль паскаля, когда все переменные определяются в начале функции и более прогресивный стиль, когда переменная объявляется максимально близко к месту использования.  Я придерживаюсь второго стиля.  

Если пользуешься IDEA то там есть эта проверка в анализаторе, но ей надо включить.
![Uploading image.png…]()

2021-02-08 19:23 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +    //3. The Secondary and Tertiary Structures of DNA http://rosalind.info/problems/revc/
Между 1 и 3 нет второй.  Даже если она тривиальная то лучше вынести её в функцию, для единообразия.

2021-02-09 10:08 UTC, darina-ovis commented on Olga_Sokolova/src/Solutions.java
> +    public static Integer getHammingDistance(String str1, String str2) throws Exception {
названия лучше давать осмысленные

2021-02-09 10:08 UTC, darina-ovis commented on Olga_Sokolova/src/Solutions.java
> +            throw new Exception("Strings length aren't equal");
лучше бросать более специфичный exception. Напрмер, IllegalArgumentException

2021-02-09 10:08 UTC, darina-ovis commented on Olga_Sokolova/src/Solutions.java
> +    }};
можно вынести в отдельный класс с константами

2021-02-09 10:08 UTC, darina-ovis commented on Olga_Sokolova/src/Solutions.java
> +            if (!(aminoAcid = codonTable.get(rna.substring(i, i + 3))).equals("Stop")) {
обычно стараются избегать магических чисел. можно 3 вынести в константы и назвать amino_acid_length. Аналогично для "Stop"

2021-02-09 10:08 UTC, darina-ovis commented on Olga_Sokolova/src/Solutions.java
> +        long current = 0L;
может, лучше подойдет ancestor, current и descendant

2021-02-09 10:08 UTC, darina-ovis commented on Olga_Sokolova/src/Solutions.java
> +    }};
лучше вынести в константы

2021-02-09 10:08 UTC, darina-ovis commented on Olga_Sokolova/src/Main.java
> +    }
Такой подход не очень масштабируемый. Чем больше задач будет добавляться, тем дольше ждать, пока все выполняться. или надо комментировать код. Простой вариант - это сделать параметр для задачи

2021-02-09 18:06 UTC, Cjkjvfnby requested changes
Задачи решены, но есть моменты которые стоит сделать лучше, прежде чем закрыть эту тему.

2021-02-09 18:06 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        return counts;
Для небольшого количества пар лучше использвать Map.of  https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html#of(K,V,K,V,K,V,K,V,K,V,K,V,K,V,K,V,K,V,K,V)
Там хитрая реализация которая поддерживает только 10 пар.

2021-02-09 18:06 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +            switch (strArray[i]) {
switch  можно заменить на Map.  strArray[i] = complementary.get(strArray[i])
Код получится более коротким и меньше шансов сделать ошибку.

2021-02-09 18:06 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        String[] strArray = str.split("");
В джаве есть тип char, он занимает намного меньше памяти чем строка.  В данном случае стоит использовать именно его.

2021-02-09 18:06 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        Collections.reverse(Arrays.asList(strArray));
Если в начале функции создать пустой массив и потом в него складывать элементы сразу по нужному индексу то можно будет избавится от добполнительной операции по разворачиванию.

2021-02-09 18:06 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        for (int i = 0; i < str1.length(); i++) {
Попробуй ради интереса через стрим и фильтр и суммирование сделать.

2021-02-09 18:06 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +            if (!(aminoAcid = codonTable.get(rna.substring(i, i + 3))).equals("Stop")) {
Строка получилась очень насыщенная. 
Можно сильно упростить ей вынесением кода в отдельные методы. 

```java
String aminoAcid = getCodon()
if (isStopCodon(codon)) {
   break
else {}
}
```

По возможности стоит избавляться от отрицания в запросах, это можно сделать просто поменяв местам код в if и else

2021-02-09 18:06 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        ArrayList<Integer> countOfChildesWithDominantOfEachGenotype = new ArrayList<>(Arrays.asList(4, 4, 4, 3, 2, 0));
List.of

2021-02-09 18:06 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        int countOfChildesWithDominant = 0;
countOfChildes Три переменные с одинаковым префиксом могут вызвать путаницу.   В данном случае немного спасает их длиннна.  Но в обще стоит избегать такого подхода.

2021-02-09 20:23 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +        int countOfChildesWithDominant = 0;
Согласна, учту в будущем

2021-02-09 20:37 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +            if (!(aminoAcid = codonTable.get(rna.substring(i, i + 3))).equals("Stop")) {
по поводу if else в данном случае, мне кажется, логичным сделать так "Если не Stop, то добавляем, иначе -break"

2021-02-10 09:38 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +        Map<String, Long> map = Arrays.stream(str.split("")).collect(Collectors.groupingBy(s -> s, Collectors.counting()));
Можно, например, так: Stream.of(str.split("")) или через chars(), но вряд ли второе проще

2021-02-10 09:40 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +        List<Long> counts = new ArrayList<>();
Учту, спасибо! Картинка не загрузилась

2021-02-10 09:48 UTC, o-sokolova commented on Olga_Sokolova/src/Main.java
> +            ex.printStackTrace();
System.err.println("Can't open file" + path);

2021-02-10 09:56 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +        return counts;
Спасибо! Тут наверное надо List.of использовать,  return List.of(map.get("A"), map.get("C"), map.get("G"), map.get("T"));. Или что-то другое имелось в виду?

2021-02-10 17:56 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        List<Long> counts = new ArrayList<>();
![image](https://user-images.githubusercontent.com/171597/107550652-5bb06580-6be2-11eb-8de0-e57b13d7443d.png)

2021-02-10 18:02 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        Map<String, Long> map = Arrays.stream(str.split("")).collect(Collectors.groupingBy(s -> s, Collectors.counting()));
`Stream.of("aaaa".toCharArray())`

Сплит это работа со строкой и разбиение её через регулярные выражения.  Это очень накладно по сравнению простой итерацией.

2021-02-10 18:03 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +            if (!(aminoAcid = codonTable.get(rna.substring(i, i + 3))).equals("Stop")) {
Отрицание это чуть более сложная операция для человеке чем его отстутствие.  А машине вообще всё равно.

2021-02-10 18:04 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        return counts;
Да здесь лучше лист, про мап это к другим участкам кода.

2021-02-11 16:31 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Main.java
> +            ex.printStackTrace();
> System.err.println("Can't open file" + path);

Это пример кода, я имел ввиду пример вывода на консоль результатов выполнения программы.

2021-02-11 16:57 UTC, Cjkjvfnby requested changes
Несколько косметических замечаний.

2021-02-11 16:57 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Constants.java
> +    public static Map<Character, Character> complementary = new HashMap<Character, Character>() {{
Здесь Map.of будет красивей. Опционально.

2021-02-11 16:57 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Main.java
> +    public static void main(String[] args) {
Было бы проще раскидать задачи по разным классам и просто запусткать main каждого класса.  Опционально.

2021-02-11 16:57 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Main.java
> +            System.err.println("Can't open file" + task9_path);
Пробеличика не хватает. IOException  может вылететь в разных случаях, можно ещё добавить `e.getMessage()`

2021-02-11 16:57 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +    static final int AMINO_ACID_LENGTH = 3;
Вдохновение для названия переменных можно брать из доменной области (ну или из текста задачи). 

В данном случае мы говорим про триплеты, они же кодоны.  Говорящие имя будет: CODON_LENGTH.

2021-02-11 16:57 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +    static final String STOP_AMINO_ACID = "Stop";
Мы говорим о вполне конкретном объекте, который имеет своё общепринятое имя и даже страницу в википедии.  Это же имя идеальный кандидат для названия переменной.

2021-02-11 16:57 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
>      public static double getCountOfDominantChildes(ArrayList<Integer> countOfCouples) {
Childes -> Children

2021-02-14 18:31 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +        Map<String, Long> map = Arrays.stream(str.split("")).collect(Collectors.groupingBy(s -> s, Collectors.counting()));
Тогда я бы сделала так: str.chars().mapToObj(c -> (char) c), 
потому что Stream.of("aaaa".toCharArray()) возвращает стрим,  содержаший один элемент - char[], то есть надо будет еще "aaaa".toCharArray() приводить к Character[]

2021-02-14 18:36 UTC, o-sokolova commented on Olga_Sokolova/src/Main.java
> +    public static void main(String[] args) {
Согласна, учту в будущем

2021-02-14 18:42 UTC, o-sokolova commented on Olga_Sokolova/src/Main.java
> +            System.err.println("Can't open file" + task9_path);
Добавила

2021-02-14 18:43 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +    static final int AMINO_ACID_LENGTH = 3;
Согласна

2021-02-14 18:45 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +    static final String STOP_AMINO_ACID = "Stop";
Исправила

2021-02-14 18:48 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
>      public static double getCountOfDominantChildes(ArrayList<Integer> countOfCouples) {
Исправлено

2021-02-14 18:49 UTC, o-sokolova commented on Olga_Sokolova/src/Main.java
> +            ex.printStackTrace();
Пример вывода результатов выполнения задач 1 и 2, если файл для 1й отсутствует:
_Can't open file dataset/rosalind_dna.txt
dataset\rosalind_dna.txt
UGGAC_

2021-02-14 21:02 UTC, Cjkjvfnby approved these changes
Спасибо, я засчитываю задачи.

2021-02-14 21:02 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Constants.java
> +    public static Map<Character, Character> complementary = Map.of('A', 'T', 'C', 'G', 'G', 'C','T', 'A');
Обычно вызов форматируют по два значения на строку, так удобнее читать.

2021-02-14 21:02 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Main.java
> +        if (fileLines != null) {
В данном случае весь блок try catch можно убрать. пусть себе падает.  Все равно после ошибки программу не делает ничего.

2021-02-14 21:02 UTC, Cjkjvfnby commented on Olga_Sokolova/src/Solutions.java
> +        return List.of(map.get('A'), map.get('C'), map.get('G'), map.get('T'));
Если передать в данный метод строку "ATG" произойдёт ужасное.

2021-02-15 08:56 UTC, o-sokolova commented on Olga_Sokolova/src/Solutions.java
> +        return List.of(map.get('A'), map.get('C'), map.get('G'), map.get('T'));
Исправлено

2021-02-15 08:57 UTC, merged