Add solution for 10 tasks
Bioinformatics-internship-EPAM/rosalind-solutions-2021 pull request #8
Opened 2021-02-08 05:03 UTC by AnastasiaShemyakinskaya

Добавила решения для следующих задач:
* Counting DNA Nucleotides
* Transcribing DNA into RNA
* Complementing a Strand of DNA
* Computing GC Content
* Counting Point Mutations
* Translating RNA into Protein
* Finding a Motif in DNA
* Finding a Shared Motif
* Calculating Protein Mass
* RNA Splicing

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam requested changes
Задачи сделаны, с решениями все в порядке.
Но я нашел 2 логические ошибки и чуть больше десятка стилистических замечаний.
Исправьте и можно переходить к проектам.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/Main.java
> +            e.printStackTrace();
`try-catch` блок внутри которого `e.printStackTrace()` почти всегда можно заменить на вынесение исключения в сигнатуру метода, тем более для main().
Стектрейс все равно напечатается, а писать несколько раз один и тот же блок не нужно будет.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/Main.java
> +        System.out.println("Task #1 Counting DNA Nucleotides");
Объединять все задачи в один класс - довольно спорное решение.
Мне кажется, гораздо проще делать на каждую задачу свой main class.
Вы можете оставить как есть, но это вряд ли удобно.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/ComputeGCTask.java
> +    private Double maxPercentage = 0.0;
Здесь лучше заменить тип на примитивный `double`, так как значение никогда не будет `null`. Ссылочные типы для примитивных значений имеет смысл использовать только при возможности `null`. В другом случае это только путает - приходится лишний раз проверять на отсутствие значения.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/ComputeGCTask.java
> +        for ( Map.Entry<String, String> entry : dnaMap.entrySet()) {
Здесь у Вас лишний пробел после `(`. Если используете IDE - попробуйте авто-форматирование кода, позволяет не задумываться о форматировании.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/CountNucleotidsTask.java
> +            map.put(symbol, countNucleotides(symbol));
Строка проходится 4 раза. Для задачи это приемлемо, но можно сделать и за один проход, да еще и короче:
```java
Map<Character, Long> frequencies = dnaChain.chars().collect(
    Collectors.groupingBy(Functions.identity(), Collectors.counting())
)
```

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/HammingDistanceTask.java
> +            throw new IllegalArgumentException("Strings are not equals");
Сообщение об ошибке не совсем верное, оно сообщает что строки не равны, но сравнивается только их длина.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/HammingDistanceTask.java
> +    public Long evaluateHammingDistance() {
Здесь тоже нет никакой необходимости оборачивать значение в ссылочный тип (почитайте, например: https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html). Поскольку `Stream.count()` возвращает `long`, лучше такой же тип и передавать дальше.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/ProteinMassTask.java
> +        return proteinString.chars().mapToDouble(c -> weights.get(String.valueOf((char)c))).sum();
Эта строчка немного тяжело читается. При работе со стримами принято разделять операции на строки, примерно так:
```java
return proteinString.chars()
    .mapToDouble(c -> weights.get(String.valueOf((char) c)))
    .sum();
```

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/ProteinTranslationTask.java
> +        Path path = Paths.get("rna_protein_table.txt");
Код чтения таблицы из текстового файла почти полностью повторяет метод `ProteinMassTask. readMassTable()`. Попробуйте избавиться от дублирования и вынести общий код в метод.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/ProteinTranslationTask.java
> +            if (!proteinChar.equals("Stop")) {
Здесь есть логическая ошибка.
Стоп-кодон должен прерывать цикл, а у Вас он продолжается.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/ProteinTranslationTask.java
> +        for (int i = 0; i < this.rnaString.length()-4; i = i + 3 ){
Здесь не очень очевидно откуда взялось число 4.
Может быть, для читаемости стоит перенести условие внутрь цикла:
```java
for (int i = 0; i < rnaString.length(); i = i + 3) {
    int codonEnd = i + 3;
    if (codonEnd >= rnaString.length()) {
        break;
    }
}
```

И еще 2 небольших замечания:
* `this.` можно убрать.
* Число 3 можно сделать именованной константой `CODON_LENGTH`. В данном случае это не обязательно, но вообще повышает читаемость.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/ReverseComplementTask.java
> +                case 'C':
Здесь отсутствует `break`. Этот код работает совсем не так как задумано.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/SharedMotifTask.java
> +        for (int i = 0; i < dnaString.length(); ++i) {
В этой строчке префиксный оператор инкремента, а в следующей - постфиксный. По сути разницы нет, а визуально есть. Лучше сделать одинаково.

2021-02-08 16:07 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/utils/FastaFile.java
> +            List<String> stringList = new ArrayList<>();
Здесь лучше дать переменным более информативные имена, например:
* `List<String> dnaChunks` вместо `strings`
* `List<String> chunkLines` вместо `stringList`

2021-02-11 04:20 UTC, AnastasiaShemyakinskaya commented
@dmitrii-adamian-at-epam, поправила замечания

2021-02-11 08:56 UTC, dmitrii-adamian-at-epam approved these changes
У меня еще два небольших замечания по стилю. Поправьте их, вливайте свою ветку и выбирайте проект.

2021-02-11 08:56 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/tasks/ProteinMassTask.java
> +        } catch (IOException e) {
Этот try-catch блок можно убрать.

2021-02-11 08:56 UTC, dmitrii-adamian-at-epam commented on Anastasia_Shemyakinskaya/src/ru/spbstu/utils/FileUtils.java
> +            ;
Эту строку лучше убрать.

2021-02-15 12:05 UTC, iporsh commented
@AnastasiaShemyakinskaya для удобства просмотра испрfвления ремарок в https://github.com/ есть кнопка "Resolve conversation"

2021-02-17 12:33 UTC, merged